#pragma once

// Generated by tools/transpose.py. Edit the .lin.py source to regenerate.
#include "math/linalg/linear_transpose.hpp"

template <class T>
std::vector<T> range_sum(std::vector<T> x, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);
template <class T>
std::vector<T> range_sum_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);
template <class T>
int range_sum_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);
template <class T>
std::vector<T> subset_zeta(std::vector<T> x);
template <class T>
std::vector<T> subset_zeta_transpose(const std::vector<T>& _lt_seed, int _lt_input_size);
template <class T>
int subset_zeta_output_size([[maybe_unused]] int _lt_input_size);
template <class T>
std::vector<T> divisor_zeta(std::vector<T> x, [[maybe_unused]] const std::vector<int>& primes);
template <class T>
std::vector<T> divisor_zeta_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<int>& primes);
template <class T>
int divisor_zeta_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<int>& primes);
template <class T>
std::vector<T> fenwick_queries(std::vector<T> x, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);
template <class T>
std::vector<T> fenwick_queries_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);
template <class T>
int fenwick_queries_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right);

template <class T>
int range_sum_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  return int(left.size());
}

template <class T>
std::vector<T> range_sum(std::vector<T> x, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_1 = (int(x.size()) + 1);
  assert(_lt_1 >= 0);
  std::vector<T> s(_lt_1);
  const int _lt_2 = int(left.size());
  assert(_lt_2 >= 0);
  std::vector<T> y(_lt_2);
  assert(((int(left.size()) == int(right.size()))));
  {
    const long long _lt_3 = 0, _lt_4 = int(x.size()), _lt_5 = 1;
    assert(_lt_5 != 0);
    const long long _lt_6 = _lt_5 > 0 ? (_lt_3 < _lt_4 ? (_lt_4 - _lt_3 - 1) / _lt_5 + 1 : 0) : (_lt_3 > _lt_4 ? (_lt_3 - _lt_4 - 1) / (-_lt_5) + 1 : 0);
    for (long long _lt_7 = 0; _lt_7 < _lt_6; ++_lt_7) {
      [[maybe_unused]] const long long i = _lt_3 + _lt_7 * _lt_5;
      s[(i + 1)] = (s[i]) * (1) + (x[i]) * (1);
    }
  }
  {
    const long long _lt_8 = 0, _lt_9 = int(left.size()), _lt_10 = 1;
    assert(_lt_10 != 0);
    const long long _lt_11 = _lt_10 > 0 ? (_lt_8 < _lt_9 ? (_lt_9 - _lt_8 - 1) / _lt_10 + 1 : 0) : (_lt_8 > _lt_9 ? (_lt_8 - _lt_9 - 1) / (-_lt_10) + 1 : 0);
    for (long long _lt_12 = 0; _lt_12 < _lt_11; ++_lt_12) {
      [[maybe_unused]] const long long i = _lt_8 + _lt_12 * _lt_10;
      y[i] = (s[right[i]]) * (1) + (s[left[i]]) * ((-(1)));
    }
  }
  assert(int(y.size()) == range_sum_output_size<T>(_lt_input_size, left, right));
  return y;
}

template <class T>
std::vector<T> range_sum_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == range_sum_output_size<T>(_lt_input_size, left, right));
  const int _lt_13 = (int(x.size()) + 1);
  assert(_lt_13 >= 0);
  std::vector<T> s(_lt_13);
  const int _lt_14 = int(left.size());
  assert(_lt_14 >= 0);
  std::vector<T> y(_lt_14);
  linear_transpose::add_to(y, _lt_seed);
  assert(((int(left.size()) == int(right.size()))));
  {
    const long long _lt_15 = 0, _lt_16 = int(left.size()), _lt_17 = 1;
    assert(_lt_17 != 0);
    const long long _lt_18 = _lt_17 > 0 ? (_lt_15 < _lt_16 ? (_lt_16 - _lt_15 - 1) / _lt_17 + 1 : 0) : (_lt_15 > _lt_16 ? (_lt_15 - _lt_16 - 1) / (-_lt_17) + 1 : 0);
    for (long long _lt_19 = _lt_18; _lt_19-- > 0;) {
      [[maybe_unused]] const long long i = _lt_15 + _lt_19 * _lt_17;
      const T _lt_20 = y[i];
      y[i] = T(0);
      s[right[i]] += _lt_20 * (1);
      s[left[i]] += _lt_20 * ((-(1)));
    }
  }
  {
    const long long _lt_21 = 0, _lt_22 = int(x.size()), _lt_23 = 1;
    assert(_lt_23 != 0);
    const long long _lt_24 = _lt_23 > 0 ? (_lt_21 < _lt_22 ? (_lt_22 - _lt_21 - 1) / _lt_23 + 1 : 0) : (_lt_21 > _lt_22 ? (_lt_21 - _lt_22 - 1) / (-_lt_23) + 1 : 0);
    for (long long _lt_25 = _lt_24; _lt_25-- > 0;) {
      [[maybe_unused]] const long long i = _lt_21 + _lt_25 * _lt_23;
      const T _lt_26 = s[(i + 1)];
      s[(i + 1)] = T(0);
      s[i] += _lt_26 * (1);
      x[i] += _lt_26 * (1);
    }
  }
  return x;
}

template <class T>
bool range_sum_check(int _lt_input_size, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, range_sum_output_size<T>(_lt_input_size, left, right),
    [&](const std::vector<T>& _lt_x) { return range_sum<T>(_lt_x, left, right); },
    [&](const std::vector<T>& _lt_y) { return range_sum_transpose<T>(_lt_y, _lt_input_size, left, right); }, _lt_trials);
}

template <class T>
int subset_zeta_output_size([[maybe_unused]] int _lt_input_size)
{
  return _lt_input_size;
}

template <class T>
std::vector<T> subset_zeta(std::vector<T> x)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  assert((((int(x.size()) > 0)) && has_single_bit(int(x.size()))));
  {
    const long long _lt_27 = 0, _lt_28 = (bit_width(int(x.size())) - 1), _lt_29 = 1;
    assert(_lt_29 != 0);
    const long long _lt_30 = _lt_29 > 0 ? (_lt_27 < _lt_28 ? (_lt_28 - _lt_27 - 1) / _lt_29 + 1 : 0) : (_lt_27 > _lt_28 ? (_lt_27 - _lt_28 - 1) / (-_lt_29) + 1 : 0);
    for (long long _lt_31 = 0; _lt_31 < _lt_30; ++_lt_31) {
      [[maybe_unused]] const long long bit = _lt_27 + _lt_31 * _lt_29;
      [[maybe_unused]] const auto d = (1 << bit);
      {
        const long long _lt_32 = 0, _lt_33 = int(x.size()), _lt_34 = (2 * d);
        assert(_lt_34 != 0);
        const long long _lt_35 = _lt_34 > 0 ? (_lt_32 < _lt_33 ? (_lt_33 - _lt_32 - 1) / _lt_34 + 1 : 0) : (_lt_32 > _lt_33 ? (_lt_32 - _lt_33 - 1) / (-_lt_34) + 1 : 0);
        for (long long _lt_36 = 0; _lt_36 < _lt_35; ++_lt_36) {
          [[maybe_unused]] const long long block = _lt_32 + _lt_36 * _lt_34;
          {
            const long long _lt_37 = block, _lt_38 = (block + d), _lt_39 = 1;
            assert(_lt_39 != 0);
            const long long _lt_40 = _lt_39 > 0 ? (_lt_37 < _lt_38 ? (_lt_38 - _lt_37 - 1) / _lt_39 + 1 : 0) : (_lt_37 > _lt_38 ? (_lt_37 - _lt_38 - 1) / (-_lt_39) + 1 : 0);
            for (long long _lt_41 = 0; _lt_41 < _lt_40; ++_lt_41) {
              [[maybe_unused]] const long long i = _lt_37 + _lt_41 * _lt_39;
              x[(i + d)] += (x[i]) * (1);
            }
          }
        }
      }
    }
  }
  assert(int(x.size()) == subset_zeta_output_size<T>(_lt_input_size));
  return x;
}

template <class T>
std::vector<T> subset_zeta_transpose(const std::vector<T>& _lt_seed, int _lt_input_size)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == subset_zeta_output_size<T>(_lt_input_size));
  linear_transpose::add_to(x, _lt_seed);
  assert((((int(x.size()) > 0)) && has_single_bit(int(x.size()))));
  {
    const long long _lt_42 = 0, _lt_43 = (bit_width(int(x.size())) - 1), _lt_44 = 1;
    assert(_lt_44 != 0);
    const long long _lt_45 = _lt_44 > 0 ? (_lt_42 < _lt_43 ? (_lt_43 - _lt_42 - 1) / _lt_44 + 1 : 0) : (_lt_42 > _lt_43 ? (_lt_42 - _lt_43 - 1) / (-_lt_44) + 1 : 0);
    for (long long _lt_46 = _lt_45; _lt_46-- > 0;) {
      [[maybe_unused]] const long long bit = _lt_42 + _lt_46 * _lt_44;
      [[maybe_unused]] const auto d = (1 << bit);
      {
        const long long _lt_47 = 0, _lt_48 = int(x.size()), _lt_49 = (2 * d);
        assert(_lt_49 != 0);
        const long long _lt_50 = _lt_49 > 0 ? (_lt_47 < _lt_48 ? (_lt_48 - _lt_47 - 1) / _lt_49 + 1 : 0) : (_lt_47 > _lt_48 ? (_lt_47 - _lt_48 - 1) / (-_lt_49) + 1 : 0);
        for (long long _lt_51 = _lt_50; _lt_51-- > 0;) {
          [[maybe_unused]] const long long block = _lt_47 + _lt_51 * _lt_49;
          {
            const long long _lt_52 = block, _lt_53 = (block + d), _lt_54 = 1;
            assert(_lt_54 != 0);
            const long long _lt_55 = _lt_54 > 0 ? (_lt_52 < _lt_53 ? (_lt_53 - _lt_52 - 1) / _lt_54 + 1 : 0) : (_lt_52 > _lt_53 ? (_lt_52 - _lt_53 - 1) / (-_lt_54) + 1 : 0);
            for (long long _lt_56 = _lt_55; _lt_56-- > 0;) {
              [[maybe_unused]] const long long i = _lt_52 + _lt_56 * _lt_54;
              const T _lt_57 = x[(i + d)];
              x[i] += _lt_57 * (1);
            }
          }
        }
      }
    }
  }
  return x;
}

template <class T>
bool subset_zeta_check(int _lt_input_size, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, subset_zeta_output_size<T>(_lt_input_size),
    [&](const std::vector<T>& _lt_x) { return subset_zeta<T>(_lt_x); },
    [&](const std::vector<T>& _lt_y) { return subset_zeta_transpose<T>(_lt_y, _lt_input_size); }, _lt_trials);
}

template <class T>
int divisor_zeta_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<int>& primes)
{
  return _lt_input_size;
}

template <class T>
std::vector<T> divisor_zeta(std::vector<T> x, [[maybe_unused]] const std::vector<int>& primes)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  {
    const auto& _lt_59 = primes;
    for (auto _lt_58 = _lt_59.begin(); _lt_58 != _lt_59.end(); ++_lt_58) {
      [[maybe_unused]] const auto& p = *_lt_58;
      {
        const long long _lt_60 = 1, _lt_61 = (((int(x.size()) - 1) / p) + 1), _lt_62 = 1;
        assert(_lt_62 != 0);
        const long long _lt_63 = _lt_62 > 0 ? (_lt_60 < _lt_61 ? (_lt_61 - _lt_60 - 1) / _lt_62 + 1 : 0) : (_lt_60 > _lt_61 ? (_lt_60 - _lt_61 - 1) / (-_lt_62) + 1 : 0);
        for (long long _lt_64 = 0; _lt_64 < _lt_63; ++_lt_64) {
          [[maybe_unused]] const long long i = _lt_60 + _lt_64 * _lt_62;
          x[(i * p)] += (x[i]) * (1);
        }
      }
    }
  }
  assert(int(x.size()) == divisor_zeta_output_size<T>(_lt_input_size, primes));
  return x;
}

template <class T>
std::vector<T> divisor_zeta_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<int>& primes)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == divisor_zeta_output_size<T>(_lt_input_size, primes));
  linear_transpose::add_to(x, _lt_seed);
  {
    const auto& _lt_66 = primes;
    for (auto _lt_65 = _lt_66.rbegin(); _lt_65 != _lt_66.rend(); ++_lt_65) {
      [[maybe_unused]] const auto& p = *_lt_65;
      {
        const long long _lt_67 = 1, _lt_68 = (((int(x.size()) - 1) / p) + 1), _lt_69 = 1;
        assert(_lt_69 != 0);
        const long long _lt_70 = _lt_69 > 0 ? (_lt_67 < _lt_68 ? (_lt_68 - _lt_67 - 1) / _lt_69 + 1 : 0) : (_lt_67 > _lt_68 ? (_lt_67 - _lt_68 - 1) / (-_lt_69) + 1 : 0);
        for (long long _lt_71 = _lt_70; _lt_71-- > 0;) {
          [[maybe_unused]] const long long i = _lt_67 + _lt_71 * _lt_69;
          const T _lt_72 = x[(i * p)];
          x[i] += _lt_72 * (1);
        }
      }
    }
  }
  return x;
}

template <class T>
bool divisor_zeta_check(int _lt_input_size, [[maybe_unused]] const std::vector<int>& primes, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, divisor_zeta_output_size<T>(_lt_input_size, primes),
    [&](const std::vector<T>& _lt_x) { return divisor_zeta<T>(_lt_x, primes); },
    [&](const std::vector<T>& _lt_y) { return divisor_zeta_transpose<T>(_lt_y, _lt_input_size, primes); }, _lt_trials);
}

template <class T>
int fenwick_queries_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  return int(kind.size());
}

template <class T>
std::vector<T> fenwick_queries(std::vector<T> x, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_73 = (n + 1);
  assert(_lt_73 >= 0);
  std::vector<T> tree(_lt_73);
  const int _lt_74 = int(kind.size());
  assert(_lt_74 >= 0);
  std::vector<T> y(_lt_74);
  assert(((int(x.size()) == (n + int(kind.size())))));
  assert((((int(left.size()) == int(kind.size()))) && ((int(right.size()) == int(kind.size())))));
  {
    const long long _lt_75 = 0, _lt_76 = n, _lt_77 = 1;
    assert(_lt_77 != 0);
    const long long _lt_78 = _lt_77 > 0 ? (_lt_75 < _lt_76 ? (_lt_76 - _lt_75 - 1) / _lt_77 + 1 : 0) : (_lt_75 > _lt_76 ? (_lt_75 - _lt_76 - 1) / (-_lt_77) + 1 : 0);
    for (long long _lt_79 = 0; _lt_79 < _lt_78; ++_lt_79) {
      [[maybe_unused]] const long long i = _lt_75 + _lt_79 * _lt_77;
      tree[(i + 1)] += (x[i]) * (1);
    }
  }
  {
    const long long _lt_80 = 1, _lt_81 = (n + 1), _lt_82 = 1;
    assert(_lt_82 != 0);
    const long long _lt_83 = _lt_82 > 0 ? (_lt_80 < _lt_81 ? (_lt_81 - _lt_80 - 1) / _lt_82 + 1 : 0) : (_lt_80 > _lt_81 ? (_lt_80 - _lt_81 - 1) / (-_lt_82) + 1 : 0);
    for (long long _lt_84 = 0; _lt_84 < _lt_83; ++_lt_84) {
      [[maybe_unused]] const long long i = _lt_80 + _lt_84 * _lt_82;
      [[maybe_unused]] const auto parent = (i + (i & (-i)));
      if (((parent <= n))) {
        tree[parent] += (tree[i]) * (1);
      }
    }
  }
  {
    const long long _lt_85 = 0, _lt_86 = int(kind.size()), _lt_87 = 1;
    assert(_lt_87 != 0);
    const long long _lt_88 = _lt_87 > 0 ? (_lt_85 < _lt_86 ? (_lt_86 - _lt_85 - 1) / _lt_87 + 1 : 0) : (_lt_85 > _lt_86 ? (_lt_85 - _lt_86 - 1) / (-_lt_87) + 1 : 0);
    for (long long _lt_89 = 0; _lt_89 < _lt_88; ++_lt_89) {
      [[maybe_unused]] const long long t = _lt_85 + _lt_89 * _lt_87;
      if (((kind[t] == 0))) {
        {
          const long long _lt_90 = 0, _lt_91 = bit_width(n), _lt_92 = 1;
          assert(_lt_92 != 0);
          const long long _lt_93 = _lt_92 > 0 ? (_lt_90 < _lt_91 ? (_lt_91 - _lt_90 - 1) / _lt_92 + 1 : 0) : (_lt_90 > _lt_91 ? (_lt_90 - _lt_91 - 1) / (-_lt_92) + 1 : 0);
          for (long long _lt_94 = 0; _lt_94 < _lt_93; ++_lt_94) {
            [[maybe_unused]] const long long b = _lt_90 + _lt_94 * _lt_92;
            if ((((left[t] & (1 << b)) == 0))) {
              [[maybe_unused]] const auto p = (((left[t] >> b) + 1) << b);
              if (((p <= n))) {
                tree[p] += (x[(n + t)]) * (1);
              }
            }
          }
        }
      } else {
        {
          const long long _lt_95 = 0, _lt_96 = bit_width(n), _lt_97 = 1;
          assert(_lt_97 != 0);
          const long long _lt_98 = _lt_97 > 0 ? (_lt_95 < _lt_96 ? (_lt_96 - _lt_95 - 1) / _lt_97 + 1 : 0) : (_lt_95 > _lt_96 ? (_lt_95 - _lt_96 - 1) / (-_lt_97) + 1 : 0);
          for (long long _lt_99 = 0; _lt_99 < _lt_98; ++_lt_99) {
            [[maybe_unused]] const long long b = _lt_95 + _lt_99 * _lt_97;
            if ((right[t] & (1 << b))) {
              y[t] += (tree[(right[t] & (~((1 << b) - 1)))]) * (1);
            }
            if ((left[t] & (1 << b))) {
              y[t] += (tree[(left[t] & (~((1 << b) - 1)))]) * ((-(1)));
            }
          }
        }
      }
    }
  }
  assert(int(y.size()) == fenwick_queries_output_size<T>(_lt_input_size, n, kind, left, right));
  return y;
}

template <class T>
std::vector<T> fenwick_queries_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == fenwick_queries_output_size<T>(_lt_input_size, n, kind, left, right));
  const int _lt_100 = (n + 1);
  assert(_lt_100 >= 0);
  std::vector<T> tree(_lt_100);
  const int _lt_101 = int(kind.size());
  assert(_lt_101 >= 0);
  std::vector<T> y(_lt_101);
  linear_transpose::add_to(y, _lt_seed);
  assert(((int(x.size()) == (n + int(kind.size())))));
  assert((((int(left.size()) == int(kind.size()))) && ((int(right.size()) == int(kind.size())))));
  {
    const long long _lt_102 = 0, _lt_103 = int(kind.size()), _lt_104 = 1;
    assert(_lt_104 != 0);
    const long long _lt_105 = _lt_104 > 0 ? (_lt_102 < _lt_103 ? (_lt_103 - _lt_102 - 1) / _lt_104 + 1 : 0) : (_lt_102 > _lt_103 ? (_lt_102 - _lt_103 - 1) / (-_lt_104) + 1 : 0);
    for (long long _lt_106 = _lt_105; _lt_106-- > 0;) {
      [[maybe_unused]] const long long t = _lt_102 + _lt_106 * _lt_104;
      if (((kind[t] == 0))) {
        {
          const long long _lt_107 = 0, _lt_108 = bit_width(n), _lt_109 = 1;
          assert(_lt_109 != 0);
          const long long _lt_110 = _lt_109 > 0 ? (_lt_107 < _lt_108 ? (_lt_108 - _lt_107 - 1) / _lt_109 + 1 : 0) : (_lt_107 > _lt_108 ? (_lt_107 - _lt_108 - 1) / (-_lt_109) + 1 : 0);
          for (long long _lt_111 = _lt_110; _lt_111-- > 0;) {
            [[maybe_unused]] const long long b = _lt_107 + _lt_111 * _lt_109;
            if ((((left[t] & (1 << b)) == 0))) {
              [[maybe_unused]] const auto p = (((left[t] >> b) + 1) << b);
              if (((p <= n))) {
                const T _lt_112 = tree[p];
                x[(n + t)] += _lt_112 * (1);
              }
            }
          }
        }
      } else {
        {
          const long long _lt_113 = 0, _lt_114 = bit_width(n), _lt_115 = 1;
          assert(_lt_115 != 0);
          const long long _lt_116 = _lt_115 > 0 ? (_lt_113 < _lt_114 ? (_lt_114 - _lt_113 - 1) / _lt_115 + 1 : 0) : (_lt_113 > _lt_114 ? (_lt_113 - _lt_114 - 1) / (-_lt_115) + 1 : 0);
          for (long long _lt_117 = _lt_116; _lt_117-- > 0;) {
            [[maybe_unused]] const long long b = _lt_113 + _lt_117 * _lt_115;
            if ((left[t] & (1 << b))) {
              const T _lt_118 = y[t];
              tree[(left[t] & (~((1 << b) - 1)))] += _lt_118 * ((-(1)));
            }
            if ((right[t] & (1 << b))) {
              const T _lt_119 = y[t];
              tree[(right[t] & (~((1 << b) - 1)))] += _lt_119 * (1);
            }
          }
        }
      }
    }
  }
  {
    const long long _lt_120 = 1, _lt_121 = (n + 1), _lt_122 = 1;
    assert(_lt_122 != 0);
    const long long _lt_123 = _lt_122 > 0 ? (_lt_120 < _lt_121 ? (_lt_121 - _lt_120 - 1) / _lt_122 + 1 : 0) : (_lt_120 > _lt_121 ? (_lt_120 - _lt_121 - 1) / (-_lt_122) + 1 : 0);
    for (long long _lt_124 = _lt_123; _lt_124-- > 0;) {
      [[maybe_unused]] const long long i = _lt_120 + _lt_124 * _lt_122;
      [[maybe_unused]] const auto parent = (i + (i & (-i)));
      if (((parent <= n))) {
        const T _lt_125 = tree[parent];
        tree[i] += _lt_125 * (1);
      }
    }
  }
  {
    const long long _lt_126 = 0, _lt_127 = n, _lt_128 = 1;
    assert(_lt_128 != 0);
    const long long _lt_129 = _lt_128 > 0 ? (_lt_126 < _lt_127 ? (_lt_127 - _lt_126 - 1) / _lt_128 + 1 : 0) : (_lt_126 > _lt_127 ? (_lt_126 - _lt_127 - 1) / (-_lt_128) + 1 : 0);
    for (long long _lt_130 = _lt_129; _lt_130-- > 0;) {
      [[maybe_unused]] const long long i = _lt_126 + _lt_130 * _lt_128;
      const T _lt_131 = tree[(i + 1)];
      x[i] += _lt_131 * (1);
    }
  }
  return x;
}

template <class T>
bool fenwick_queries_check(int _lt_input_size, [[maybe_unused]] int n, [[maybe_unused]] const std::vector<int>& kind, [[maybe_unused]] const std::vector<int>& left, [[maybe_unused]] const std::vector<int>& right, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, fenwick_queries_output_size<T>(_lt_input_size, n, kind, left, right),
    [&](const std::vector<T>& _lt_x) { return fenwick_queries<T>(_lt_x, n, kind, left, right); },
    [&](const std::vector<T>& _lt_y) { return fenwick_queries_transpose<T>(_lt_y, _lt_input_size, n, kind, left, right); }, _lt_trials);
}
