#pragma once

// Generated by tools/transpose.py. Edit the .lin.py source to regenerate.
#include "math/linalg/linear_transpose.hpp"

template <class T>
std::vector<T> fixed_convolution(std::vector<T> x, [[maybe_unused]] const std::vector<T>& kernel);
template <class T>
std::vector<T> fixed_convolution_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<T>& kernel);
template <class T>
int fixed_convolution_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<T>& kernel);
template <class T>
std::vector<T> fixed_remainder(std::vector<T> x, [[maybe_unused]] const std::vector<T>& divisor);
template <class T>
std::vector<T> fixed_remainder_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<T>& divisor);
template <class T>
int fixed_remainder_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<T>& divisor);
template <class T>
std::vector<T> fourier(std::vector<T> x);
template <class T>
std::vector<T> fourier_transpose(const std::vector<T>& _lt_seed, int _lt_input_size);
template <class T>
int fourier_output_size([[maybe_unused]] int _lt_input_size);
template <class T>
std::vector<T> inverse_fourier(std::vector<T> x);
template <class T>
std::vector<T> inverse_fourier_transpose(const std::vector<T>& _lt_seed, int _lt_input_size);
template <class T>
int inverse_fourier_output_size([[maybe_unused]] int _lt_input_size);
template <class T>
std::vector<T> newton_basis(std::vector<T> x, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node);
template <class T>
std::vector<T> newton_basis_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node);
template <class T>
int newton_basis_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node);
template <class T>
std::vector<T> evaluate_tree(std::vector<T> x, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count);
template <class T>
std::vector<T> evaluate_tree_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count);
template <class T>
int evaluate_tree_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count);

template <class T>
int fixed_convolution_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<T>& kernel)
{
  return ((((_lt_input_size == 0)) || ((int(kernel.size()) == 0))) ? 0 : ((_lt_input_size + int(kernel.size())) - 1));
}

template <class T>
std::vector<T> fixed_convolution(std::vector<T> x, [[maybe_unused]] const std::vector<T>& kernel)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_1 = (x.empty() || (kernel).empty() ? 0 : int(x.size()) + int((kernel).size()) - 1);
  assert(_lt_1 >= 0);
  std::vector<T> y(_lt_1);
  y = convolution(x, kernel);
  assert(int(y.size()) == fixed_convolution_output_size<T>(_lt_input_size, kernel));
  return y;
}

template <class T>
std::vector<T> fixed_convolution_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<T>& kernel)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == fixed_convolution_output_size<T>(_lt_input_size, kernel));
  const int _lt_2 = (x.empty() || (kernel).empty() ? 0 : int(x.size()) + int((kernel).size()) - 1);
  assert(_lt_2 >= 0);
  std::vector<T> y(_lt_2);
  linear_transpose::add_to(y, _lt_seed);
  linear_transpose::add_to(x, linear_transpose::convolution_transpose(y, kernel, int(x.size())));
  std::fill(y.begin(), y.end(), T(0));
  return x;
}

template <class T>
bool fixed_convolution_check(int _lt_input_size, [[maybe_unused]] const std::vector<T>& kernel, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, fixed_convolution_output_size<T>(_lt_input_size, kernel),
    [&](const std::vector<T>& _lt_x) { return fixed_convolution<T>(_lt_x, kernel); },
    [&](const std::vector<T>& _lt_y) { return fixed_convolution_transpose<T>(_lt_y, _lt_input_size, kernel); }, _lt_trials);
}

template <class T>
int fixed_remainder_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<T>& divisor)
{
  return (int(divisor.size()) - 1);
}

template <class T>
std::vector<T> fixed_remainder(std::vector<T> x, [[maybe_unused]] const std::vector<T>& divisor)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_3 = (int((divisor).size()) - 1);
  assert(_lt_3 >= 0);
  std::vector<T> y(_lt_3);
  y = linear_transpose::polynomial_mod(x, divisor);
  assert(int(y.size()) == fixed_remainder_output_size<T>(_lt_input_size, divisor));
  return y;
}

template <class T>
std::vector<T> fixed_remainder_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<T>& divisor)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == fixed_remainder_output_size<T>(_lt_input_size, divisor));
  const int _lt_4 = (int((divisor).size()) - 1);
  assert(_lt_4 >= 0);
  std::vector<T> y(_lt_4);
  linear_transpose::add_to(y, _lt_seed);
  linear_transpose::add_to(x, linear_transpose::polynomial_mod_transpose(y, divisor, int(x.size())));
  std::fill(y.begin(), y.end(), T(0));
  return x;
}

template <class T>
bool fixed_remainder_check(int _lt_input_size, [[maybe_unused]] const std::vector<T>& divisor, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, fixed_remainder_output_size<T>(_lt_input_size, divisor),
    [&](const std::vector<T>& _lt_x) { return fixed_remainder<T>(_lt_x, divisor); },
    [&](const std::vector<T>& _lt_y) { return fixed_remainder_transpose<T>(_lt_y, _lt_input_size, divisor); }, _lt_trials);
}

template <class T>
int fourier_output_size([[maybe_unused]] int _lt_input_size)
{
  return _lt_input_size;
}

template <class T>
std::vector<T> fourier(std::vector<T> x)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_5 = int(x.size());
  assert(_lt_5 >= 0);
  std::vector<T> y(_lt_5);
  y = linear_transpose::ntt_forward(x);
  assert(int(y.size()) == fourier_output_size<T>(_lt_input_size));
  return y;
}

template <class T>
std::vector<T> fourier_transpose(const std::vector<T>& _lt_seed, int _lt_input_size)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == fourier_output_size<T>(_lt_input_size));
  const int _lt_6 = int(x.size());
  assert(_lt_6 >= 0);
  std::vector<T> y(_lt_6);
  linear_transpose::add_to(y, _lt_seed);
  linear_transpose::add_to(x, linear_transpose::ntt_transpose(y));
  std::fill(y.begin(), y.end(), T(0));
  return x;
}

template <class T>
bool fourier_check(int _lt_input_size, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, fourier_output_size<T>(_lt_input_size),
    [&](const std::vector<T>& _lt_x) { return fourier<T>(_lt_x); },
    [&](const std::vector<T>& _lt_y) { return fourier_transpose<T>(_lt_y, _lt_input_size); }, _lt_trials);
}

template <class T>
int inverse_fourier_output_size([[maybe_unused]] int _lt_input_size)
{
  return _lt_input_size;
}

template <class T>
std::vector<T> inverse_fourier(std::vector<T> x)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_7 = int(x.size());
  assert(_lt_7 >= 0);
  std::vector<T> y(_lt_7);
  y = linear_transpose::intt_forward(x);
  assert(int(y.size()) == inverse_fourier_output_size<T>(_lt_input_size));
  return y;
}

template <class T>
std::vector<T> inverse_fourier_transpose(const std::vector<T>& _lt_seed, int _lt_input_size)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == inverse_fourier_output_size<T>(_lt_input_size));
  const int _lt_8 = int(x.size());
  assert(_lt_8 >= 0);
  std::vector<T> y(_lt_8);
  linear_transpose::add_to(y, _lt_seed);
  linear_transpose::add_to(x, linear_transpose::intt_transpose(y));
  std::fill(y.begin(), y.end(), T(0));
  return x;
}

template <class T>
bool inverse_fourier_check(int _lt_input_size, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, inverse_fourier_output_size<T>(_lt_input_size),
    [&](const std::vector<T>& _lt_x) { return inverse_fourier<T>(_lt_x); },
    [&](const std::vector<T>& _lt_y) { return inverse_fourier_transpose<T>(_lt_y, _lt_input_size); }, _lt_trials);
}

template <class T>
int newton_basis_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node)
{
  return _lt_input_size;
}

template <class T>
std::vector<T> newton_basis(std::vector<T> x, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  [[maybe_unused]] const auto n = int(x.size());
  const int _lt_9 = n;
  assert(_lt_9 >= 0);
  std::vector<T> y(_lt_9);
  if (((n == 1))) {
    y[0] = (x[0]) * (1);
  } else {
    const int _lt_10 = ((n / 2) - 0);
    assert(_lt_10 >= 0);
    std::vector<T> a(_lt_10);
    const int _lt_11 = (n - (n / 2));
    assert(_lt_11 >= 0);
    std::vector<T> b(_lt_11);
    const int _lt_12 = newton_basis_output_size<T>(int(a.size()), products, (2 * node));
    assert(_lt_12 >= 0);
    std::vector<T> c(_lt_12);
    const int _lt_13 = newton_basis_output_size<T>(int(b.size()), products, ((2 * node) + 1));
    assert(_lt_13 >= 0);
    std::vector<T> d(_lt_13);
    const int _lt_14 = (d.empty() || (products[(2 * node)]).empty() ? 0 : int(d.size()) + int((products[(2 * node)]).size()) - 1);
    assert(_lt_14 >= 0);
    std::vector<T> e(_lt_14);
    a = linear_transpose::slice(x, 0, (n / 2));
    b = linear_transpose::slice(x, (n / 2), n);
    c = newton_basis<T>(a, products, (2 * node));
    d = newton_basis<T>(b, products, ((2 * node) + 1));
    e = convolution(d, products[(2 * node)]);
    {
      const long long _lt_15 = 0, _lt_16 = int(c.size()), _lt_17 = 1;
      assert(_lt_17 != 0);
      const long long _lt_18 = _lt_17 > 0 ? (_lt_15 < _lt_16 ? (_lt_16 - _lt_15 - 1) / _lt_17 + 1 : 0) : (_lt_15 > _lt_16 ? (_lt_15 - _lt_16 - 1) / (-_lt_17) + 1 : 0);
      for (long long _lt_19 = 0; _lt_19 < _lt_18; ++_lt_19) {
        [[maybe_unused]] const long long i = _lt_15 + _lt_19 * _lt_17;
        y[i] += (c[i]) * (1);
      }
    }
    {
      const long long _lt_20 = 0, _lt_21 = int(e.size()), _lt_22 = 1;
      assert(_lt_22 != 0);
      const long long _lt_23 = _lt_22 > 0 ? (_lt_20 < _lt_21 ? (_lt_21 - _lt_20 - 1) / _lt_22 + 1 : 0) : (_lt_20 > _lt_21 ? (_lt_20 - _lt_21 - 1) / (-_lt_22) + 1 : 0);
      for (long long _lt_24 = 0; _lt_24 < _lt_23; ++_lt_24) {
        [[maybe_unused]] const long long i = _lt_20 + _lt_24 * _lt_22;
        y[i] += (e[i]) * (1);
      }
    }
  }
  assert(int(y.size()) == newton_basis_output_size<T>(_lt_input_size, products, node));
  return y;
}

template <class T>
std::vector<T> newton_basis_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == newton_basis_output_size<T>(_lt_input_size, products, node));
  [[maybe_unused]] const auto n = int(x.size());
  const int _lt_25 = n;
  assert(_lt_25 >= 0);
  std::vector<T> y(_lt_25);
  linear_transpose::add_to(y, _lt_seed);
  if (((n == 1))) {
    const T _lt_26 = y[0];
    y[0] = T(0);
    x[0] += _lt_26 * (1);
  } else {
    const int _lt_27 = ((n / 2) - 0);
    assert(_lt_27 >= 0);
    std::vector<T> a(_lt_27);
    const int _lt_28 = (n - (n / 2));
    assert(_lt_28 >= 0);
    std::vector<T> b(_lt_28);
    const int _lt_29 = newton_basis_output_size<T>(int(a.size()), products, (2 * node));
    assert(_lt_29 >= 0);
    std::vector<T> c(_lt_29);
    const int _lt_30 = newton_basis_output_size<T>(int(b.size()), products, ((2 * node) + 1));
    assert(_lt_30 >= 0);
    std::vector<T> d(_lt_30);
    const int _lt_31 = (d.empty() || (products[(2 * node)]).empty() ? 0 : int(d.size()) + int((products[(2 * node)]).size()) - 1);
    assert(_lt_31 >= 0);
    std::vector<T> e(_lt_31);
    {
      const long long _lt_32 = 0, _lt_33 = int(e.size()), _lt_34 = 1;
      assert(_lt_34 != 0);
      const long long _lt_35 = _lt_34 > 0 ? (_lt_32 < _lt_33 ? (_lt_33 - _lt_32 - 1) / _lt_34 + 1 : 0) : (_lt_32 > _lt_33 ? (_lt_32 - _lt_33 - 1) / (-_lt_34) + 1 : 0);
      for (long long _lt_36 = _lt_35; _lt_36-- > 0;) {
        [[maybe_unused]] const long long i = _lt_32 + _lt_36 * _lt_34;
        const T _lt_37 = y[i];
        e[i] += _lt_37 * (1);
      }
    }
    {
      const long long _lt_38 = 0, _lt_39 = int(c.size()), _lt_40 = 1;
      assert(_lt_40 != 0);
      const long long _lt_41 = _lt_40 > 0 ? (_lt_38 < _lt_39 ? (_lt_39 - _lt_38 - 1) / _lt_40 + 1 : 0) : (_lt_38 > _lt_39 ? (_lt_38 - _lt_39 - 1) / (-_lt_40) + 1 : 0);
      for (long long _lt_42 = _lt_41; _lt_42-- > 0;) {
        [[maybe_unused]] const long long i = _lt_38 + _lt_42 * _lt_40;
        const T _lt_43 = y[i];
        c[i] += _lt_43 * (1);
      }
    }
    linear_transpose::add_to(d, linear_transpose::convolution_transpose(e, products[(2 * node)], int(d.size())));
    std::fill(e.begin(), e.end(), T(0));
    linear_transpose::add_to(b, newton_basis_transpose<T>(d, int(b.size()), products, ((2 * node) + 1)));
    std::fill(d.begin(), d.end(), T(0));
    linear_transpose::add_to(a, newton_basis_transpose<T>(c, int(a.size()), products, (2 * node)));
    std::fill(c.begin(), c.end(), T(0));
    assert(0 <= (n / 2) && (n / 2) <= n && n <= int(x.size()));
    for (int _lt_44 = 0; _lt_44 < int(b.size()); ++_lt_44) x[((n / 2)) + _lt_44] += b[_lt_44];
    std::fill(b.begin(), b.end(), T(0));
    assert(0 <= 0 && 0 <= (n / 2) && (n / 2) <= int(x.size()));
    for (int _lt_45 = 0; _lt_45 < int(a.size()); ++_lt_45) x[(0) + _lt_45] += a[_lt_45];
    std::fill(a.begin(), a.end(), T(0));
  }
  return x;
}

template <class T>
bool newton_basis_check(int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, newton_basis_output_size<T>(_lt_input_size, products, node),
    [&](const std::vector<T>& _lt_x) { return newton_basis<T>(_lt_x, products, node); },
    [&](const std::vector<T>& _lt_y) { return newton_basis_transpose<T>(_lt_y, _lt_input_size, products, node); }, _lt_trials);
}

template <class T>
int evaluate_tree_output_size([[maybe_unused]] int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count)
{
  return count;
}

template <class T>
std::vector<T> evaluate_tree(std::vector<T> x, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count)
{
  [[maybe_unused]] const int _lt_input_size = x.size();
  const int _lt_46 = count;
  assert(_lt_46 >= 0);
  std::vector<T> y(_lt_46);
  if (((count == 1))) {
    {
      const long long _lt_47 = 0, _lt_48 = int(x.size()), _lt_49 = 1;
      assert(_lt_49 != 0);
      const long long _lt_50 = _lt_49 > 0 ? (_lt_47 < _lt_48 ? (_lt_48 - _lt_47 - 1) / _lt_49 + 1 : 0) : (_lt_47 > _lt_48 ? (_lt_47 - _lt_48 - 1) / (-_lt_49) + 1 : 0);
      for (long long _lt_51 = 0; _lt_51 < _lt_50; ++_lt_51) {
        [[maybe_unused]] const long long i = _lt_47 + _lt_51 * _lt_49;
        y[0] += (x[i]) * ((1) * T((-products[node][0]).pow(i)));
      }
    }
  } else {
    const int _lt_52 = (int((products[(2 * node)]).size()) - 1);
    assert(_lt_52 >= 0);
    std::vector<T> a(_lt_52);
    const int _lt_53 = (int((products[((2 * node) + 1)]).size()) - 1);
    assert(_lt_53 >= 0);
    std::vector<T> b(_lt_53);
    const int _lt_54 = evaluate_tree_output_size<T>(int(a.size()), products, (2 * node), (count / 2));
    assert(_lt_54 >= 0);
    std::vector<T> c(_lt_54);
    const int _lt_55 = evaluate_tree_output_size<T>(int(b.size()), products, ((2 * node) + 1), (count / 2));
    assert(_lt_55 >= 0);
    std::vector<T> d(_lt_55);
    a = linear_transpose::polynomial_mod(x, products[(2 * node)]);
    b = linear_transpose::polynomial_mod(x, products[((2 * node) + 1)]);
    c = evaluate_tree<T>(a, products, (2 * node), (count / 2));
    d = evaluate_tree<T>(b, products, ((2 * node) + 1), (count / 2));
    {
      const long long _lt_56 = 0, _lt_57 = (count / 2), _lt_58 = 1;
      assert(_lt_58 != 0);
      const long long _lt_59 = _lt_58 > 0 ? (_lt_56 < _lt_57 ? (_lt_57 - _lt_56 - 1) / _lt_58 + 1 : 0) : (_lt_56 > _lt_57 ? (_lt_56 - _lt_57 - 1) / (-_lt_58) + 1 : 0);
      for (long long _lt_60 = 0; _lt_60 < _lt_59; ++_lt_60) {
        [[maybe_unused]] const long long i = _lt_56 + _lt_60 * _lt_58;
        y[i] += (c[i]) * (1);
        y[((count / 2) + i)] += (d[i]) * (1);
      }
    }
  }
  assert(int(y.size()) == evaluate_tree_output_size<T>(_lt_input_size, products, node, count));
  return y;
}

template <class T>
std::vector<T> evaluate_tree_transpose(const std::vector<T>& _lt_seed, int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count)
{
  assert(_lt_input_size >= 0);
  std::vector<T> x(_lt_input_size);
  assert(int(_lt_seed.size()) == evaluate_tree_output_size<T>(_lt_input_size, products, node, count));
  const int _lt_61 = count;
  assert(_lt_61 >= 0);
  std::vector<T> y(_lt_61);
  linear_transpose::add_to(y, _lt_seed);
  if (((count == 1))) {
    {
      const long long _lt_62 = 0, _lt_63 = int(x.size()), _lt_64 = 1;
      assert(_lt_64 != 0);
      const long long _lt_65 = _lt_64 > 0 ? (_lt_62 < _lt_63 ? (_lt_63 - _lt_62 - 1) / _lt_64 + 1 : 0) : (_lt_62 > _lt_63 ? (_lt_62 - _lt_63 - 1) / (-_lt_64) + 1 : 0);
      for (long long _lt_66 = _lt_65; _lt_66-- > 0;) {
        [[maybe_unused]] const long long i = _lt_62 + _lt_66 * _lt_64;
        const T _lt_67 = y[0];
        x[i] += _lt_67 * ((1) * T((-products[node][0]).pow(i)));
      }
    }
  } else {
    const int _lt_68 = (int((products[(2 * node)]).size()) - 1);
    assert(_lt_68 >= 0);
    std::vector<T> a(_lt_68);
    const int _lt_69 = (int((products[((2 * node) + 1)]).size()) - 1);
    assert(_lt_69 >= 0);
    std::vector<T> b(_lt_69);
    const int _lt_70 = evaluate_tree_output_size<T>(int(a.size()), products, (2 * node), (count / 2));
    assert(_lt_70 >= 0);
    std::vector<T> c(_lt_70);
    const int _lt_71 = evaluate_tree_output_size<T>(int(b.size()), products, ((2 * node) + 1), (count / 2));
    assert(_lt_71 >= 0);
    std::vector<T> d(_lt_71);
    {
      const long long _lt_72 = 0, _lt_73 = (count / 2), _lt_74 = 1;
      assert(_lt_74 != 0);
      const long long _lt_75 = _lt_74 > 0 ? (_lt_72 < _lt_73 ? (_lt_73 - _lt_72 - 1) / _lt_74 + 1 : 0) : (_lt_72 > _lt_73 ? (_lt_72 - _lt_73 - 1) / (-_lt_74) + 1 : 0);
      for (long long _lt_76 = _lt_75; _lt_76-- > 0;) {
        [[maybe_unused]] const long long i = _lt_72 + _lt_76 * _lt_74;
        const T _lt_77 = y[((count / 2) + i)];
        d[i] += _lt_77 * (1);
        const T _lt_78 = y[i];
        c[i] += _lt_78 * (1);
      }
    }
    linear_transpose::add_to(b, evaluate_tree_transpose<T>(d, int(b.size()), products, ((2 * node) + 1), (count / 2)));
    std::fill(d.begin(), d.end(), T(0));
    linear_transpose::add_to(a, evaluate_tree_transpose<T>(c, int(a.size()), products, (2 * node), (count / 2)));
    std::fill(c.begin(), c.end(), T(0));
    linear_transpose::add_to(x, linear_transpose::polynomial_mod_transpose(b, products[((2 * node) + 1)], int(x.size())));
    std::fill(b.begin(), b.end(), T(0));
    linear_transpose::add_to(x, linear_transpose::polynomial_mod_transpose(a, products[(2 * node)], int(x.size())));
    std::fill(a.begin(), a.end(), T(0));
  }
  return x;
}

template <class T>
bool evaluate_tree_check(int _lt_input_size, [[maybe_unused]] const std::vector<std::vector<T>>& products, [[maybe_unused]] int node, [[maybe_unused]] int count, int _lt_trials = 8)
{
  return linear_transpose::check<T>(_lt_input_size, evaluate_tree_output_size<T>(_lt_input_size, products, node, count),
    [&](const std::vector<T>& _lt_x) { return evaluate_tree<T>(_lt_x, products, node, count); },
    [&](const std::vector<T>& _lt_y) { return evaluate_tree_transpose<T>(_lt_y, _lt_input_size, products, node, count); }, _lt_trials);
}
